# CircleCI 2.0 configuration file
version: 2.1

orbs:
  codacy: codacy/base@0.3.3

workflows:
  version: 2
  compile_test_deploy:
    jobs:
    - codacy/checkout_and_version:
        write_sbt_version: true
    - codacy/sbt:
        name: populate_cache
        cmd: sbt ";set scalafmtUseIvy in ThisBuild := false;update"
        requires:
          - codacy/checkout_and_version
    - codacy/sbt:
        name: check_fmt
        cmd: sbt ";scalafmt::test;test:scalafmt::test;sbt:scalafmt::test"
        requires:
          - populate_cache
    - codacy/sbt:
        name: compile
        cmd: sbt compile
        requires:
          - populate_cache
    - codacy/sbt:
        name: test_and_coverage
        cmd: |
          if [ -z ${CODACY_PROJECT_TOKEN+x} ]; then
            echo "CODACY_PROJECT_TOKEN not found. Skipping send coverage to Codacy."
            sbt test
          else
            sbt ";coverage;test;coverageReport;coverageAggregate;codacyCoverage"
          fi
        requires:
          - compile
          - check_fmt
    - codacy/sbt:
        name: publish
        context: CodacyAWS
        cmd: sbt ";retrieveGPGKeys;+publishSigned;sonatypeReleaseAll"
        requires:
          - test_and_coverage
        filters:
          branches:
            only:
            - master
    - codacy/tag_version:
        name: tag_version
        context: CodacyAWS
        filters:
          branches:
            only:
            - master
        requires:
          - publish
